api:
  image: mersocarlin/aspnet
  command: dnx web
  volumes:
    - ./BankService/BankService.Api:/app
  ports:
    - "5000:5000"
  links:
    - mongo

mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - mongo-aspnet-core-docker:/data/db